- frontend/src/containers/pages/AuthoringTool/ToolBar/ToolBar.js
- frontend/src/styling/ToolBar.module.scss
---
title: "[VPS-007] Add labels in toolbar"
---
Based on the user story: "As a user I'd like to clearly interpret what each tool in the toolbar is"
Added labels next to the icons in the scene editing toolbar.
Minimal to none
> VPS-007/Add labels in toolbar

- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioCanvas.js
- frontend/src/containers/pages/PlayScenarioPage/__tests__/__snapshots__/PlayScenarioCanvas.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/__tests__/__snapshots__/PlayScenarioPage.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/progressBar.js
users want to know current progress in their scenarios
added a progress bar component when playing the scenario
Nothing, because it is an empty component with a set value for the progress, it hasnt been connected to the backend yet
> VPS-011/ add progress bar

- README.md
- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.js
When editing a scene, the user receives no response when clicking the save button.
When the user clicks the save button, it saves the content of the scene and returns the user to the scene menu.
Little to none. Only added exit feature, as save implementation already present
> VPS-012/save and close functionality

- frontend/src/components/SideBar.js
- frontend/src/components/__tests__/__snapshots__/SideBar.test.js.snap
- frontend/src/containers/App.js
- frontend/src/containers/pages/DashboardPage.js
- frontend/src/containers/pages/__tests__/__snapshots__/ScenarioSelectionPage.test.js.snap
- frontend/src/firebase/StaffAuth.js
Create a page that’s only accessible to lecturers when they log in where they can see the dashboard (and other students can't access it when they log in)
Created a button that leads to an empty dashboard page. Tried to reuse the top bar that was already created but there were errors.
We are able to determine whether or not the current user is a lecturer, depending on the email domain. However, security is an issue as it is all done on the frontend.
Slight security risk since authentication is currently in frontend but we will be moving it to the backend.
> Vps 029/authentication and dashboard button

- frontend/src/components/SideBar.js
- frontend/src/components/__tests__/__snapshots__/SideBar.test.js.snap
- frontend/src/containers/App.js
- frontend/src/containers/pages/DashboardPage.js
- frontend/src/containers/pages/__tests__/__snapshots__/ScenarioSelectionPage.test.js.snap
- frontend/src/firebase/StaffAuth.js
Need a dummy page to test endpoint. This branch is behind the main
Merge from main since previous issue have created a button to take you to a dummy page.
Nothing because I'm merging from the main.
> Branch is behind main

- backend/src/db/daos/scenarioDao.js
- backend/src/db/models/scenario.js
- backend/src/routes/api/scenario.js
> Vps 030/scenario durations

- backend/src/db/daos/staffDao.js
- backend/src/db/models/staff.js
- backend/src/routes/api/index.js
- backend/src/routes/api/staff.js
- frontend/src/components/SideBar.js
- frontend/src/components/__tests__/__snapshots__/SideBar.test.js.snap
- frontend/src/containers/App.js
- frontend/src/containers/pages/DashboardPage.js
- frontend/src/containers/pages/__tests__/__snapshots__/ScenarioSelectionPage.test.js.snap
- frontend/src/context/AuthenticationContextProvider.js
- frontend/src/enums/route.access.level.js
- frontend/src/firebase/ProtectedRoute.js
- frontend/src/firebase/StaffAuth.js
- frontend/src/hooks/crudHooks.js
Dashboard should only be viewed by lecturers, but is currently accessible to everyone
Create a page that’s only accessible to lecturers when they log in where they can see the dashboard (and other students can't access it when they log in)
Low (potentially security risk?)
> VPS-029/Lecturer Authentication for Dashboard

- backend/src/db/daos/userDao.js
- backend/src/routes/api/scenario.js
- frontend/src/components/SideBar.js
- frontend/src/components/__tests__/__snapshots__/SideBar.test.js.snap
- frontend/src/containers/pages/Dashboard/DashboardPage.js
- frontend/src/containers/pages/SceneSelectionPage.js
- frontend/src/containers/pages/__tests__/__snapshots__/ScenarioSelectionPage.test.js.snap
- frontend/src/containers/pages/__tests__/__snapshots__/SceneSelectionPage.test.js.snap
- frontend/src/styling/DashboardScoreboard.module.scss
Finishing up Issue #29 regarding the dashboard button that shows up only if the user is authenticated as staff.
Added a dashboard button to the Scene Selection page. I also kept the button on the Scenario Selection page, but made it disabled unless the user clicks on a scenario.
Minimal
> VPS-029/Move Dashboard Button

- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/ComponentProperties/TextPropertiesComponent.js
- frontend/src/containers/pages/AuthoringTool/Components/TextComponent.js
Added new component onDoubleClick to TextComponent Component
Added function handleDoubleClick in TextComonemnt Component which allows user to edit text component on double click
Function searches for textarea on the page. If another textarea is implemented the function may not know which textarea it should edit
> add double click to text box to edit the text component

- frontend/src/containers/pages/AuthoringTool/Canvas/componentResolver.js
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/SceneSettings.js
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/componentPropertiesResolver.js
- frontend/src/containers/pages/AuthoringTool/ToolBar/ToolBarActions.js
- frontend/src/containers/pages/AuthoringTool/ToolBar/ToolBarData.js
- frontend/src/containers/pages/PlayScenarioPage/componentResolver.js
described in task #59 
- fix bugs found
1. input element can't have null value
2. shrink effect for input elements have to be an boolean (i.e. shrink = false or shrink = true)
but a string was given instead of boolean.
- add button for adding speechboxes
- create function to add a speechbox to SceneContext's components list
- add a case to resolve speechboxes (in all componentResolver files) so that:
-   they show on scene canvas
-   their properties show on canvas sidebar
-   they show on playScene
no bugs found when run locally.
Tests haven't been passing for a while so a test failure doesn't mean this code definitely has an issue.
So will ignore for this task but will try and get the tests passing before starting a different user story 🧪🧪🧪
This …
> VPS-059/add speechbox via button

- .github/workflows/eslint.yml
- .github/workflows/prettier.yml
- .github/workflows/unit_tests.yml
- backend/src/routes/api/staff.js
As in #81, the github actions ESLint, Prettier, and Tests were failing. 
The tests were configured to use node version 12, but as mentioned in the readme this project uses node version 14. I updated this, and fixed a minor linter error in the backend (missing semicolon and comma).
This PR shouldn't bring any risk.
However, the frontend tests display themselves as working but give numerous warnings about lack of `act(...)`. I believe this is coming from some side effects in the ContextProviders not being explicitly mentioned in the tests, which could theoretically behave badly without being caught by the tests. I'm not knowledgeable enough to fix this right now, and getting the tests working again is pretty useful so I'm just PR'ing as is.
(It might be nicer to squash & merge as I did a …
> Vps 081/fixing tests

- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/__tests__/__snapshots__/CanvasSideBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/__tests__/__snapshots__/SceneSettings.test.js.snap
- frontend/src/containers/pages/AuthoringTool/ToolBar/__tests__/__snapshots__/ToolBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/__tests__/__snapshots__/AuthoringToolPage.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/__tests__/__snapshots__/PlayScenarioCanvas.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/__tests__/__snapshots__/PlayScenarioPage.test.js.snap
- frontend/src/containers/pages/__tests__/__snapshots__/LoginPage.test.js.snap
- frontend/src/styling/CanvasSideBar.module.scss
- frontend/src/styling/ChooseBackgroundModal.module.scss
Some tests are still failing after the last PR #95, which fixed the node version in the tests to address #81.
These failing tests were due to commit #76 and #79, both of which changed some parts of the UI, and as such the snapshots used in testing had to be updated too. The latter PR also had two stray spaces which caused the prettier to fail. 
Fixed formatting and updated snapshots
If these updated snapshots contain incorrect code, then our tests from now on will let through, and in fact require, these bugs. It's important that each modified snapshot is manually verified to be accurate in code review. 
> [VPS-081] Update CI Snapshots

- frontend/src/components/TimerComponent/PopUp.js
- frontend/src/components/TimerComponent/index.js
#62 
- Added red non-intrusive pop-up on bottom right corner which pops up when user has 30 seconds left
- Pop-up warns user "You have less than 30 seconds left!"
- 
- If user has placed anything under the pop-up, it will be hidden while the pop-up is shown.
- [*] Wiki Documentation is written and up to date
> Vps 062/popup screen

- frontend/src/components/newUID.js
- frontend/src/containers/pages/ScenarioSelectionPage.js
- frontend/src/containers/pages/SceneSelectionPage.js
Needed to allow the teacher to upload a csv of users which would be uploaded to mongoDB
Parses CSV and uploads each user to MongoDB
> CSV goes to mongoDB

- .github/workflows/deploy-dev.yml
> test hooks by changing comments

- README.md
Updated ReadMe as the .env files are no longer accessible via the link.
Edited the .md file.
None
Myself (bad practice)
> [VPS-#130] Updating ReadMe.

- README.md
- wiki/Onboarding/Downloading-Packages.md
- wiki/Onboarding/Git-Conventions.md
- wiki/Onboarding/Running-A-Local-Build.md
- wiki/Onboarding/Test-And-CI-CD.md
**Changes:**
- Tidying up stuff and added documentation for the onboarding of the 2024 VPS Team. Also moved it from cluttering up the ReadMe.
- Have added Dhruv, Jordan, and Jin as contributors with the intention of each developer adding themselves as an onboarding task
Potential risks that this PR might brings:
- may mess with the list of contributors (I don't know what I'm doing when it comes to HTML :P)
- TBD
> Updated Documentation and Contributors Section

- README.md
Tommy is missing on readme contributor
Added Tommy to the contributor table in the readme file
Merge confilct with other 131 branches
> VPS-131/Added Tommy to contributors

- README.md
John's profile missing from ReadMe contributor's list
Added John to ReadMe
Conflicts with other 131 branches
- Jordan B
> VPS-131/added John to readMe contributors section

- frontend/src/components/DashedCard.jsx
- frontend/src/components/__tests__/DashedCard.test.js
- frontend/src/components/__tests__/__snapshots__/DashedCard.test.js.snap
- frontend/src/containers/pages/__tests__/__snapshots__/SceneSelectionPage.test.js.snap
- frontend/src/styling/ListContainer.module.scss
The create scene button need to have a + in the middle of it
Added two boxes to form a +
Potential styling issue
> Added the plus sign

- README.md
Atul's profile is missing from the ReadMe contributor's list.
Added Atul to the contributors section on README.md
Conflicts with other 131 branches.
> Added Atul to the contributors section of the README file

- frontend/src/components/CreateScenarioCard.jsx
- frontend/src/components/SideBar.jsx
- frontend/src/containers/pages/ScenarioSelectionPage.jsx
- frontend/src/styling/CreateScenarioCard.module.scss
scenario can not be named when during creation
added a popup card that user can input a name when creating a new scenario 
merge conflict with other frontend branches
> VPS 137/create scenario with name

- README.md
Hartej's profile missing from the contributors section.
Added Hartej to the contributors section of the README.
Conflicts with other 131 branches.
Jordan
> [VPS 131] add hartej to contributors

- README.md
Subeen's profile missing from ReadMe contributor's list.
Added Subeen to the contributors section on README.md
Conflicts with other 131 branches.
> VPS-131/Added Subeen to readme contributors

- backend/src/db/models/group.js
We need a database schema for groups so that we can implement things related to groups (making groups, attaching notes to groups, etc)
Created a `group.js` file inside `backend/src/db/models/` that implements the schema for the database, which can then be exported to be used.
This is a new Schema without any dependencies inside of the project as of now, so it shouldn't conflict with anything that already exists. 
> VPS-154/implemented the database schema for groups

- backend/src/db/daos/noteDao.js
- backend/src/db/models/note.js
- backend/src/routes/api/index.js
- backend/src/routes/api/note.js
- frontend/src/components/SideBar.jsx
- wiki/backend-api.md
There's no backend structure for note feature
Created note schema in db and basic backend api
Potential bug with db operations which may delete other information
> Vps 151/notes-backend

- backend/src/db/daos/groupDao.js
- backend/src/db/daos/noteDao.js
- backend/src/routes/api/group.js
- backend/src/routes/api/note.js
- frontend/src/components/Note.jsx
- frontend/src/components/NotesDisplayCard.jsx
- frontend/src/components/PlayPageNoteButton.jsx
- frontend/src/containers/pages/InvalidRolePage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPageMulti.jsx
- frontend/src/styling/Note.module.scss
- frontend/src/styling/NotesDisplayCard.module.scss
User need to be able to view and edit note in the invalid scene page/ user can create new note
Add note component to the invalid scene page and add a add button for user to create new note
N/A
> Vps 189/notes in invalid scene page

- README.md
> Tidied Readme Table

- frontend/src/components/NotesDisplayCard.jsx
- frontend/src/containers/App.jsx
- frontend/src/containers/pages/InvalidRolePage.jsx
- frontend/src/containers/pages/ManageGroups/ManageGroupsPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioResolver.jsx
This PR aims to address three main issues:
- Manage groups table not fully showing all users
- CSV upload not giving any feedback on success/failure
- Notes menu not displaying via the invalid role page.
CSV upload now informs the user on outcome via toast messages.
The view notes button is more prominently displayed for usability.
This is a last minute change with minimal testing other than through the main critical path for milestone 1 - i.e. CSV upload -> scene permissions edit -> simple play demo. There could be untested bugs, and breaking changes.
> [VPS-24M1] Last minute fixes for Milestone One

- frontend/src/context/AuthenticationContextProvider.jsx
Logging out results in infinite redirect loop
Replaced login function with a popup version. Fixes redirect loop.
May break login
> VPS-8/signin firebase function

- frontend/src/containers/pages/DesyncPage.jsx
"Back to Scenarios" button on desync page redirects to an empty page.
Change the button function to a refresh, which forces the remount of the `SceneResolver` component which redirects back to the singleplayer/multiplayer play components.
None.
> [Vps 20] Desync Button Fix

- backend/src/db/models/resource.js
There was no database schema for resources in the codebase. Therefore, we did not have an effective and consistent way of storing resources for use in the application.
Implemented a mongoose database schema for resources and documented it on the Confluence page titled Resources Database Schema.
This doesn't have a risk of conflict with the current codebase as nothing is referring to it, and the implementation is not dependent on any of the code in our current codebase.
> [VPS-24] feat: implemented the mongoose database schema for resources

- backend/src/db/models/user.js
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPageMulti.jsx
url used abs localhost:5000
removed domain so that axios can append the one from .env file
None.
Jin
> Minor Navigation Bug Fixes

- frontend/src/components/NotesDisplayCard.jsx
- frontend/src/components/PlayPageNoteButton.jsx
- frontend/src/components/PlayPageSideButton.jsx
- frontend/src/components/ResourcesDisplayCard.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPageMulti.jsx
- frontend/src/styling/Note.module.scss
- frontend/src/styling/NotesDisplayCard.module.scss
- frontend/src/styling/PlayPageSideButton.module.scss
There's no way for a player to access resouces when playing a scenario
Add a resouces button to the play scenario page
Potential key press event conflict
> Vps 26/create resourse button fix

- frontend/src/containers/pages/LoginPage.jsx
- frontend/src/firebase/ProtectedRoute.jsx
… url once authorised
When logging in using the downloaded link, after a successful login the player is redirected to the home page instead of the start of the scenario.
The link pasted is stored in the URL as `?redirect=URL`. Once the login is authorised the user is redirected to the link posted. If there is no link, the URL is completely empty i.e no `?redirect=URL`, and redirects to the main page instead.
Shouldn't be any problems.
> VPS-16/redirect-after-login

- backend/src/routes/api/navigate/group.js
Notes are not being cleared when resetting a group
Delete all note object and the note id list in the group when resetting
Misdeleteing of wanted notes
> Vps 36/clear notes when reset

- backend/src/middleware/firebaseAuth.js
- backend/src/routes/api/group.js
- backend/src/routes/api/note.js
- frontend/src/components/Note.jsx
- frontend/src/components/NotesDisplayCard.jsx
- frontend/src/hooks/crudHooks.jsx
The Note backend has been using post method for every opeartion.
Switch to appropriate methods by creating new auth crud hooks.
> Vps 44/clean up notes

- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioCanvas.jsx
Before and next buttons buggy. Counter blocked on chrome
Removed both
May break auth tool
> Vps 56/remove before next buttons authoring

- backend/src/routes/api/navigate/group.js
- frontend/src/features/playScenario/PlayScenarioPageMulti.jsx
Reset not working
Reset the addFlags and removeFlags state in the frontend
Might break reset
> VPS-60/Reset wasnt working

- backend/src/routes/api/user.js
- only emails with certain domains could access the VPS, so testing emails (aka ending in .gmail.com) couldn't.
- added `allowedEmails` set, which means any manual emails in the set can login to VPS
- handling of emails for login
> Fix Emails Loading

- frontend/src/features/status/InvalidRolePage.jsx
_Old Design for Reference_
Proposed Improvements to the Invalid Roles Page UI:
- More visual hierarchy (e.g. colour, font size, font weight) so that the more important information stands out
- Too much whitespace (the font size could be larger)
- The buttons may look better side by side and should be styled consistently (same size)
New Proposed Invalid Roles Page UI
- more user friendly messages displayed
- use of colour and text styles to make the important information stand out
- consistent styling for the two buttons
- better use of space
The invalid role page is a independent page that doesn't interact with any other pages information so it shouldn't have much risk
> feat: improved UI for the invalid role page

- .github/workflows/deploy-dev.yml
Updates deployment pipeline to use node v20
> ops: update deployment pipeline script to node v20.

- frontend/src/features/playScenario/PlayScenarioCanvas.jsx
- frontend/src/features/playScenario/PlayScenarioPage.jsx
- frontend/src/features/playScenario/PlayScenarioPageMulti.jsx
- frontend/src/features/playScenario/components/PlayPageSideButton/PlayPageSideButton.module.scss
- frontend/src/index.css
- frontend/tailwind.config.js
Changed the colours for the play page side menu tooltips, from a transparent to a black:
vs
Changed the background of the main play page from a light grey to white, to reflect the same colours used in the authoring tool.
No risks
> Minor Play Page UI Fixes

- frontend/src/features/groups/TopBar.jsx
Upload/download button had no spacing between it
Implemented padding by actually giving the buttons a stylesheet. Mimicked the topbar in another page.
Might not have worked  
> Group Topbar Styling

- .github/workflows/deploy.staging.yml
Changed secret to arg on deployment script
> fix: changed secret to arg

- .all-contributorsrc
- README.md
> chore: add @richmantan as a contributor.

- .all-contributorsrc
- README.md
> docs: add mike to contributor list

- .all-contributorsrc
- README.md
> added Hazik to contributors

- .all-contributorsrc
- README.md
> docs: add oorja to the contributor list

- backend/src/routes/api/group.js
- frontend/src/features/groups/ManageGroupsPage.jsx
**Original Ticket**
https://wdcc-vps.atlassian.net/browse/VPS-110?linkSource=email
This PR focuses on issues regarding error handling with group creation, which don't appear to function as intended (implementation seems to be there but doesn't work properly when actually testing).
Turns out, the function doesn't actually return when there's a validation error. Fixed this issue and also made some tweaks to try improve the error messages seen by the user. Reading through the commit messages and their associated descriptions is probably most useful.
uh, hopefully nothing breaks?
> fix: validate group data csv upload (110)

- frontend/src/features/authoring/CanvasSideBar/ComponentProperties/ButtonPropertiesComponent.jsx
- frontend/src/features/authoring/CanvasSideBar/ComponentProperties/SpeechTextPropertiesComponent.jsx
- frontend/src/features/authoring/CanvasSideBar/ComponentProperties/TextPropertiesComponent.jsx
- frontend/src/features/authoring/components/ButtonComponent.jsx
- frontend/src/features/authoring/components/ColourPickerComponent.jsx
- frontend/src/features/authoring/components/SpeechTextComponent.jsx
- frontend/src/features/authoring/components/TextComponent.jsx
- frontend/src/utils/colourUtils.jsx
- package.json
- yarn.lock
Options for possible colours of buttons, text, and speech text are very limited.
Added a colour picker so users can choose exactly what colour they want. 
Increased complexity may lead to potential performance overhead.
> VPS-117/add_colour_picker

- .all-contributorsrc
- README.md
> docs: add kelvin to contributors list

- .all-contributorsrc
- README.md
> docs: add becky to contributor list

- .all-contributorsrc
- README.md
> docs: add moksh to the contributor list

- frontend/src/features/authoring/ToolBar/Background/ChooseBackgroundSubMenu.jsx
- frontend/src/features/authoring/ToolBar/Background/UploadImage.jsx
- frontend/src/features/authoring/ToolBar/UploadAudio.jsx
Tooltips needed on the required buttons such as "Upload Image" etc.
Added tooltips to such buttons
None noticeable. Did not delete anything this time.
> feat: add tooltips for image and audio upload options

- backend/package.json
- backend/src/db/daos/scenarioDao.js
- backend/src/routes/api/scenario.js
- backend/yarn.lock
- frontend/.prettierrc.js
- frontend/index.html
- frontend/src/components/StateVariables/CreateStateOperation.jsx
- frontend/src/components/StateVariables/CreateStateVariable.jsx
- frontend/src/components/StateVariables/EditStateOperation.jsx
- frontend/src/components/StateVariables/EditStateVariable.jsx
- frontend/src/components/StateVariables/EditingTooltips.jsx
- frontend/src/components/StateVariables/StateOperationForm.jsx
- frontend/src/components/StateVariables/StateVariableForm.jsx
- frontend/src/components/StateVariables/migrationUtils.js
- frontend/src/context/ScenarioContextProvider.jsx
State variables were using names as identifiers, which caused issues when users renamed variables or when duplicate names existed. This made state operations fragile and prone to breaking when variables were modified.
- Implemented UUID-based identification for state variables with automatic generation in `CreateStateVariable.jsx` and migration utilities in `migrationUtils.js`
- Added full backward compatibility with automatic migration handled in `ScenarioContextProvider.jsx`
- Enhanced lookup system in `EditStateOperation.jsx` to support both UUID-based (new format) and name-based (legacy format) references
- Updated backend support in `scenarioDao.js` and API routes in `scenario.js` to handle both identifier types
- Improved error handling with user-friendly "State Variable Not Found" …
> State variable to use UUID

- frontend/.prettierrc.js
- frontend/index.html
- frontend/src/features/authoring/CanvasSideBar/ComponentProperties/TextPropertiesComponent.jsx
- frontend/src/features/authoring/components/ColourPickerComponent.jsx
the color picker tool was not formatted properly
added padding so that thw 2 elements stay seperate
none that i am aware of.
> Fixed the authoring tool formatting 

- frontend/src/features/authoring/AuthoringToolPage.jsx
No autosave currently exists.
Added an autosave feature where 2 seconds after the user stops editing, their changes are saved.
> Vps 87/autosave inconsistent

- backend/src/db/daos/groupDao.js
- backend/src/db/daos/userDao.js
- backend/src/db/models/group.js
- backend/src/db/models/user.js
- backend/src/routes/api/navigate/group.js
- backend/src/routes/api/navigate/user.js
We're finally at the stage where we can start implementing state variables and operations in solo and group playthroughs. Currently we're concerned with initialising the state variables.
A relatively short PR from me this week, basically just saving a state variable map/array to the User/Group models when a scenario is played for the first time.
User
Group
Can't rly think of any
> Vps 156/set up state variables

- backend/src/db/daos/sceneDao.js
- backend/src/routes/api/scene.js
- frontend/package.json
- frontend/src/context/SceneContextProvider.jsx
- frontend/src/features/authoring/SceneNavigator/SceneListItem.jsx
- frontend/src/features/authoring/SceneNavigator/SceneNavigator.jsx
- frontend/src/features/authoring/SceneNavigator/SceneNavigator.module.scss
- frontend/yarn.lock
Cannot drag and drop scenes in a scenario to reorder them.
Add functionality to drag and drop scenes to easily reorder them.
- State order may become inconsistent between frontend and backend.
- Animation bugs when dragging scenes around.
> VPS-85/reorder_scenes_in_scenario
