- backend/src/db/daos/sceneDao.js
- backend/src/db/models/scene.js
- backend/src/routes/api/scene.js
- frontend/src/components/TimerComponent/Notification.js
- frontend/src/components/TimerComponent/ShowCounter.js
- frontend/src/components/TimerComponent/index.js
- frontend/src/components/TimerComponent/styles.css
- frontend/src/components/TimerComponent/useCountdown.js
- frontend/src/components/__tests__/__snapshots__/SideBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.js
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/SceneSettings.js
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/__tests__/__snapshots__/CanvasSideBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/__tests__/__snapshots__/SceneSettings.test.js.snap
- frontend/src/containers/pages/AuthoringTool/ToolBar/__tests__/__snapshots__/ToolBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/__tests__/__snapshots__/AuthoringToolPage.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioCanvas.js
- frontend/src/containers/pages/PlayScenarioPage/__tests__/__snapshots__/PlayScenarioCanvas.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/__tests__/__snapshots__/PlayScenarioPage.test.js.snap
- frontend/src/containers/pages/PlayScenarioPage/progressBar.js
- frontend/src/containers/pages/__tests__/__snapshots__/ScenarioSelectionPage.test.js.snap
- frontend/src/containers/pages/__tests__/__snapshots__/SceneSelectionPage.test.js.snap
To be able to add a time constant to the scene. After the timer ends, the scene can either end or prompt for restart. Based on Issue #22
MVP for this story is being able to add a timer for each scene, allowing the editor to customise how much time a user can spend on any given scene. At the end of the timer there will be a prompt (either pop-up stopping the scenario or prompting for a restart).
Low risk
- **There isn't a clear way for users to indicate that they don't need a timer for the scene.** At the moment, setting it to 0 and not entering a value does this, but this could cause confusion in the future. Matthew suggested potentially adding a 'no time limit checkbox'. 
-  **Material UI Shrink label overlap.** Since the shrink is managed manually, adding any '-' or '+' symbols (which …
> VPS-022/Timer

- frontend/src/components/SideBar.js
In Sidebar.js Under createScenario function, called extra endpoint to create an empty scene. By having an empty scene the thumbnail of the scenario would be fine.
Empty Scenario's thumbnail would be an error page.
On creation of a new scenario also create an empty scene,
No potential risk.
One thing to note is user can still delete their scenes and leave a scenario empty and cause the same issue.
This solution is under the assumption user will not do that
> [VPS-037] - Created empty scene when scenario is created

- backend/src/index.js
- frontend/src/hooks/crudHooks.js
- The 1st error in issue #78 occurs because [options requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) don't have cors enabled by default. 
- The 2nd error in issue #78 occurs because when the options requests fail they don't return a response. Our error catching relied on a response key that may not exist (like this case).
- changes close #78 
1. For 1st issue, simply enable cors for option requests.
2. For 2nd issue, check if response exists on error before accessing keys within response.
Might not work. 
I've simulated locally how the issues are occurring in the deployed dev version of the site and then confirmed that these fixes resolved the simulated bug. Only way to test further is to deploy a test version of the site and push changes there first.
Who …
> VPS-078/bugs🪲 - CORS & error response undefined

- frontend/src/components/ListContainer.js
- frontend/src/containers/pages/ScenarioSelectionPage.js
- frontend/src/containers/pages/SceneSelectionPage.js
As described in tasks #66 , #67, we want to be able to double click the previews for a scene or scenario to edit it.
- Added new property `onItemDoubleClick` to `ListContainer` component.
- Changed `ListContainer`'s click handling to call above method when double clicked (determined by [event.default](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail) = 2)
- Added function `editScenario()` in `ScenarioSelectionPage`, parallelling `editScene()` in `SceneSelectionPage`
- Set `onItemDoubleClick` of the `ListContainer`s in the SelectionPages to the above methods respectively.
Any other code that uses the `ListContainer` component may need to adjust its behavior, providing an `onItemDoubleClick` method. This doesn't occur anywhere else in the codebase though.
Also there is slight …
> Vps 066/scene scenario double click

- backend/src/db/daos/sceneDao.js
- backend/src/db/models/scene.js
- backend/src/routes/api/scene.js
- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.js
- frontend/src/containers/pages/AuthoringTool/SceneNavigator/SceneListItem.js
- frontend/src/containers/pages/AuthoringTool/SceneNavigator/SceneNavigator.js
- frontend/src/containers/pages/AuthoringTool/SceneNavigator/SceneTagCustomization.js
- frontend/src/containers/pages/AuthoringTool/SceneNavigator/SceneTagInput.js
- frontend/src/containers/pages/AuthoringTool/SceneNavigator/__tests__/__snapshots__/SceneNavigator.test.js.snap
- frontend/src/containers/pages/AuthoringTool/__tests__/__snapshots__/AuthoringToolPage.test.js.snap
- frontend/src/context/SceneContextProvider.js
- frontend/src/styling/SceneNavigator.module.scss
#124 
continuing #125 
this saves tags to database when changed and reads from database too.
also implemented a default "No tag" 
> [VPS-121] Retrieve and Save scene tags to database

- backend/src/db/daos/groupDao.js
- backend/src/routes/api/group.js
- backend/src/routes/api/index.js
We need to track the path of a group within a scenario, so that when users open the scenario they are given the correct current scene that their group has reached.
Created a new API endpoint at `/group/path` with both a post and get request, the first of which adds a scene to the path and the second of which retrieves the most recent scene of that path. To make sure users don't overwrite each other, added simple checking and race condition handling using transactions.
Could introduce conflicts with branch [VPS-154/csv-to-groups](https://github.com/UoaWDCC/VPS/tree/VPS-154/csv-to-groups) that will need to be resolved.
Jordan, Jin
> Vps 157/track-group-path

- backend/.eslintrc.json
- backend/src/db/daos/groupDao.js
- backend/src/db/daos/userDao.js
- backend/src/db/models/user.js
- backend/src/routes/api/group.js
- backend/src/routes/api/user.js
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioResolver.jsx
A user's last visited scene doesn't save, so they cant play through a scenario across different times or across different devices.
- Add a new field on the user db schema that stores the path for multiple scenarios
- Add a route for updating this path as the user moves across scenes
- Change the user/scenario/data route to give the current scene for users as well as groups 
Shouldn't bring any risks, as the existing route is only used in one place which has been updated accordingly.
> Vps 174/single scenario last scene

- backend/src/routes/api/group.js
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/CustomPropertyInputStyles/CustomCheckBoxStyles.js
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/SceneSettings.jsx
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/__tests__/__snapshots__/CanvasSideBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/__tests__/__snapshots__/SceneSettings.test.js.snap
- frontend/src/containers/pages/AuthoringTool/__tests__/__snapshots__/AuthoringToolPage.test.js.snap
- frontend/src/context/ScenarioContextProvider.jsx
- frontend/src/styling/CanvasSideBar.module.scss
Need to implement a UI to select roles for a scenario which takes in roles that have been given.
**Backend**
- Created a backend API endpoint at `api/group/scenario/:scenarioId/roleList` which gets the role list for a specific scenario.
**Frontend**
- Created a frontend request that retrieves the role list from `api/group/scenario/:scenarioId/roleList` and gives it in the scenario context provider.
_Usage of API endpoint_
_Usage of role list context_
- In the scene settings, there is a `Select` dropdown with checkboxes for every role which allows users to select what roles can participate in the scene. The roles that are selected are displayed. If no roles are available, the user is prompted with a message.
_Checkbox  example_
_Select Display example_
_No Roles Message example_
May have …
> VPS-165/roles for scenes UI

- backend/.eslintrc.json
- frontend/.eslintrc.json
This PR aims to disable compile errors on Prettier errors.
The reasoning being that refusing to compile on prettier errors only serves to slow down dev.
> chore: disable compile errors on prettier error.

- frontend/src/containers/pages/LoginPage.jsx
- frontend/src/containers/pages/__tests__/__snapshots__/LoginPage.test.js.snap
Bug where browsers that don't allow non-click default popups which prevents current login for testing.
added skeleton login page. a button that calls the login function.
may break login
> Adding skeleton login page

- backend/src/routes/api/__tests__/sceneApi.test.js
- backend/src/routes/api/scene.js
- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.jsx
- frontend/src/context/ScenarioContextProvider.jsx
- frontend/src/context/SceneContextProvider.jsx
Currently a lot of API endpoints are not protected with Auth, causing problems
Protected API endpoints with Auth on the backend. 
Ensure frontend API calls are using Auth so they work with the protection changes.
May break the whole application
> [VPS-15] Fix Vulnerable API Endpoints

- backend/src/routes/api/navigate/group.js
- backend/src/routes/api/navigate/index.js
- backend/src/routes/api/navigate/user.js
- frontend/src/containers/pages/AuthoringTool/Canvas/componentResolver.jsx
- frontend/src/containers/pages/AuthoringTool/ToolBar/ToolBarActions.jsx
- frontend/src/containers/pages/AuthoringTool/ToolBar/ToolBarData.jsx
- frontend/src/containers/pages/AuthoringTool/ToolBar/__tests__/__snapshots__/ToolBar.test.js.snap
- frontend/src/containers/pages/AuthoringTool/__tests__/__snapshots__/AuthoringToolPage.test.js.snap
- frontend/src/containers/pages/DesyncPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioCanvas.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPageMulti.jsx
- frontend/src/containers/pages/PlayScenarioPage/componentResolver.jsx
There isn't a way for users to reset their progress in scenarios
Created two new endpoints `/navigate/user/reset` and `/navigate/group/reset` for singleplayer and multiplayer mode respectively. These endpoints perform some validation, the same as the other navigate endpoints plus a check for whether the scene actually has a reset button, and then set the pointers back to empty (as if the scenarios haven't been accessed yet).
Added the ability to add a reset button the authoring tool:
May risk breaking playing the scenarios
> Vps 17/user reset button

- backend/src/db/models/group.js
- backend/src/db/models/resource.js
- backend/src/routes/api/group.js
There was no way of checking the current active flags of a group.
Added a property called `currentFlags` to the group schema so that each group can keep track of their currently active flags.
Minimal risk as no code depends on the `currentFlags` property and the property is not required.
> Vps 24/adding flags to groups

- frontend/src/components/ResetConfirmationModal.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioCanvas.jsx
The reset button currently allows players to reset the scenario without confirmation, risking accidental resets that affect the whole team.
Add a confirmation modal that appears when a player clicks the "Reset" button. The modal informs the player that if you click reset, the entire scenario will restart from the beginning, and all team members will need to go through the scenario again.
The two buttons would be:
- Reset Scenario: Resets the scenario as intended.
- Cancel: Closes the modal with no further action.
There would still be a slight risk that players could mistakenly confirm the reset.
> Vps 39/reset confirmation modal

- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPage.jsx
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPageMulti.jsx
When a user clicks the reset button, and another user also clicks it just after, they aren't desynced.
Correctly handle the 409 conflict response sent by the backend when desync occurs, so that it sets it as an error state in the component and hence reroutes the user to the desync page on the next render.
No risks.
> VPS-35/Reset button desync

- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/ComponentProperties/ButtonPropertiesComponent.jsx
- frontend/src/containers/pages/AuthoringTool/CanvasSideBar/ComponentProperties/__tests__/__snapshots__/ButtonPropertiesComponent.test.js.snap
- frontend/src/containers/pages/AuthoringTool/ToolBar/ToolBarActions.jsx
- frontend/src/styling/CanvasSideBar.module.scss
In the authoring tool, the "Button" component should have a new property called "Flags" where the author can update the flag actions that a button causes when it is pressed. It should have a dropdown list, where all possible flags are displayed and can be selected. 
If there are no flags, there should be a text prompting the user to add flags.
Added the property and made it a dropdown list where the author can choose which flag action is active for that button:
The user is also able to add flags themselves. When a new flag is added, two new options are added to the dropdown list (`add {newFlag}` and `remove {newFlag}`). 
If there are no flags, then a text prompting the user to add flags is shown:
Not too many risks, this one is relatively isolated and only the button component was …
> Vps 32/UI button for flags

- backend/src/routes/api/navigate/group.js
- backend/src/routes/api/navigate/index.js
- backend/src/routes/api/scene.js
- frontend/src/containers/pages/PlayScenarioPage/PlayScenarioPageMulti.jsx
When we navigate between scenes, we don't know which resources are visible to that group at that point in time.
- When we reset the scenario, the current flags field in the group schema is updated to an empty list.
- When the scene change happens, the API endpoint to get the list of visible resources is called.
- A new API endpoint was added at `/api/navigate/group/resources/:groupId` to get the list of currently visible resources for that group.
TODO:
- the logic for adding the visible resources to the list needs to be implemented (currently returns just an empty list)
- Could break scene crawling
> Vps 46/linking resources to flags

- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.jsx
- frontend/src/containers/pages/AuthoringTool/ToolBar/Background/UploadImage.jsx
- frontend/src/firebase/storage.js
Buggy image upload in authoring tool
Fixed save and close button to have a delay
Fixed uploadFile function in `storage.js` so that it returns a promise instead of just the url, so the image always gets uploaded first
Could break image upload
> VPS-50/fix image bug

- backend/src/routes/api/navigate/group.js
Evergreen flags are not considered if the group flag list is empty (the resources were only fetched when there were flags in the group list).
Removed the condition of group flags being non-empty for the resource fetch to occur.
Should not conflict with anything in the code base
> [VPS-52] fix: evergreen resources are fetched even when the group flag list is empty

- frontend/src/containers/pages/AuthoringTool/AuthoringToolPage.jsx
AuthoringToolPage
Images do not get saved correctly when saving quickly and leaving
Added await to the savescene() 
Might break images
> VPS-53/Image Upload Issue

- backend/src/routes/api/navigate/group.js
- frontend/src/features/playScenario/PlayScenarioCanvas.jsx
- frontend/src/features/playScenario/PlayScenarioPageMulti.jsx
Reset button wasn't working correctly
https://wdcc-vps.atlassian.net/jira/software/projects/VPS/boards/2?selectedIssue=VPS-60
Separated the delete all flags and delete all paths into separate functions:
May break the reset functionality
> VPS-60/reset button fix

- frontend/src/components/ListContainer/ListContainer.jsx
- frontend/src/features/status/InvalidRolePage.jsx
- package.json
- yarn.lock
Fixes unintended behaviour where the a white screen is shown instead of the invalid roles page.
_"Also, refreshing causes you to get stuck on the invalid role page, and doesn’t allow you to move on even if another group member plays through their part (hack is to remove that part from the url but that won’t work for a test class for obvs reasons)."_
The invalid roles page does provide a button to attempt to play the scenario again - we essentially bypass the need for a manual browser refresh.
- This PR bundles in a tiny fix to make the thumbnails display correctly on the **Assigned scenarios** list. Furthermore - assigned scenarios will open the scenario when clicked, instead of giving the option to be edited (which would be an invalid action).
> fix: Fix invalid roles page not displaying

- frontend/package.json
- frontend/tailwind.config.js
- frontend/yarn.lock
We are currently trying to update the UI of the project and we are wanting to use Daisy UI components in the project.
Adding DaisyUI to the tailwing config file should allow everyone to use Daisy components by adding pieces of code like this:
`<button class="btn">Button</button>`
Could possibly make somethings look different right now but once we choose the correct theme, everything should look better
> VPS-45/Daisy UI Plugin

- frontend/src/features/authoring/CanvasSideBar/SceneSettings.jsx
The Dashboard Timer was not removed from the Scene view in the authoring tool despite it not being used anymore.
Removed the dashboard timer from the authoring tool side bar.
Could potentially break components that rely on the timer attribute.
> fix(frontend/authoring-tool): deleted the timer component that was not used in the authoring tool

- backend/src/middleware/errorHandler.js
- backend/src/routes/api/navigate/group.js
- backend/src/routes/api/navigate/index.js
- backend/src/routes/api/navigate/user.js
- backend/src/routes/api/resources.js
- backend/src/routes/api/user.js
import statements were causing errors due to missing js exts.
added them
No risk
> fix: add missing `.js` extension to imports

- frontend/src/features/sceneSelection/SceneSelectionPage.jsx
When renaming a scene from the scene selection page in the authoring tool, the scene breaks (all components deleted and components cannot be added). This was because `scene.component` became `NULL` when renaming a scene from the scene selection page.
The solution was to pass through the `component` field in the PUT request so that components is also updated in the renamed scene.
Should not break anything as the component properties already existed (we just didn't update it)
> Fix for the bug: when renaming a scene, the scene breaks (scene.component becomes null)

- frontend/src/features/playScenario/PlayScenarioResolver.jsx
Route was still defined and imported the non-existent page
removed the import and route
None
> fix: remove `DesyncPage` route being defined in app

- backend/src/db/db-connect.js
- backend/src/index.js
The backend was crashing because the pathname was still using the old commonjs way and didnt work with esm.
changed it to use functions built with esm.
None.
> fix: pathname used in express initialisation

- backend/src/db/daos/scenarioDao.js
- frontend/src/context/ScenarioContextProvider.jsx
- frontend/src/features/scenarioSelection/ScenarioSelectionPage.jsx
- frontend/src/hooks/crudHooks.jsx
- Fixes a server crash when making a role list query for an invalid scenario ID.
- Removes redundant console log (logging assigned scenarios) that was spamming console on every rerender.
This is a _potential_ fix for the following bug bounty:
However, as backend nor network request logs were gathered, **we cannot verify for sure**.
Current thinking is that an invalid role list request was made on login, crashing the backend. Consequently, this makes subsequent requests fail with a `ERR_CONNECTION_REFUSED`, before the HTTP protocol can even send a request.
> fix: fix server crash on invalid scenario id role list req

- backend/src/routes/api/user.js
The email validation wasn't blocking non whitelisted emails and domains, but rather letting everything through.
Fixed the conditional that was structured incorrectly.
No Risk.
> fix: wrong conditionals in email validation

- frontend/src/features/authoring/CanvasSideBar/SceneSettings.jsx
- frontend/src/features/sceneSelection/SceneSelectionPage.jsx
- frontend/src/utils/sceneUtils.js
Scene names were not checked properly, leading to some names being duplicated. 
Created a utils file that checks to see the uniqueness/duplicates for each name, make it so that work for every type of scene naming/changing.
It may mess with the the naming conventions, but otherwise it should work.
> Prevent duplicate scene naming

- frontend/src/features/dashboard/Dashboard.jsx
- frontend/src/features/dashboard/ViewGroup.jsx
- frontend/src/features/dashboard/components/CustomTypes.jsx
- frontend/src/features/dashboard/components/DashTopBar.jsx
- frontend/src/features/dashboard/components/Graph.jsx
- frontend/src/features/dashboard/components/Table.jsx
- frontend/src/features/dashboard/components/TableHelper.js
- frontend/src/features/dashboard/components/TablePaginationAction.jsx
- frontend/src/features/dashboard/components/TableStyle.js
The author has no way to tell the exact path students took if the students backtracked. They also don't have a way to view the state variables of the group.
- Added a path navigator to the graph, which allows the user to step through the path of the group, highlighting the node (could maybe add play pause for auto step-through in future)
- Added a table under the group member table that displays the state variables of the group.
> feat: add path navigator & table for state variable
